// COPYRIGHT LICENSE: This information contains sample code provided in
// source code form. You may copy, modify, and distribute these sample
// programs in any form without payment to IBM for the purposes of
// developing, using, marketing or distributing application programs
// conforming to the application programming interface for the operating
// platform for which the sample code is written. Notwithstanding anything
// to the contrary, IBM PROVIDES THE SAMPLE SOURCE CODE ON AN "AS IS" BASIS
// AND IBM DISCLAIMS ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING, BUT NOT
// LIMITED TO, ANY IMPLIED WARRANTIES OR CONDITIONS OF MERCHANTABILITY,
// SATISFACTORY QUALITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, AND ANY
// WARRANTY OR CONDITION OF NON-INFRINGEMENT. IBM SHALL NOT BE LIABLE FOR ANY
// DIRECT, INDIRECT, INCIDENTAL, SPECIAL OR CONSEQUENTIAL DAMAGES ARISING OUT
// OF THE USE OR OPERATION OF THE SAMPLE SOURCE CODE. IBM HAS NO OBLIGATION
// TO PROVIDE MAINTENANCE, SUPPORT, UPDATES, ENHANCEMENTS OR MODIFICATIONS TO
// THE SAMPLE SOURCE CODE.
//
// (C) Copyright IBM Corp. 2008, 2011.
// All Rights Reserved. Licensed Materials - Property of IBM.
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.04.17 at 08:08:10 AM EDT 
//


package com.ibm.ws.commsvc.webservice.impl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="addressOfRecord" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="callStatus" type="{}CallState"/>
 *         &lt;element name="callerAddressOfRecord" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="calleeAddressOfRecord" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="callId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="callFailureReason" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "CallStatus")
public class CallStatus {

    @XmlElement(required = true)
    protected String addressOfRecord;
    @XmlElement(required = true)
    protected CallState callStatus;
    @XmlElement(required = true)
    protected String callerAddressOfRecord;
    @XmlElement(required = true)
    protected String calleeAddressOfRecord;
    @XmlElement(required = true)
    protected String callId;
    @XmlElement(required = true)
    protected String callFailureReason;

    /**
     * Gets the value of the addressOfRecord property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddressOfRecord() {
        return addressOfRecord;
    }

    /**
     * Sets the value of the addressOfRecord property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddressOfRecord(String value) {
        this.addressOfRecord = value;
    }

    /**
     * Gets the value of the callStatus property.
     * 
     * @return
     *     possible object is
     *     {@link CallState }
     *     
     */
    public CallState getCallStatus() {
        return callStatus;
    }

    /**
     * Sets the value of the callStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link CallState }
     *     
     */
    public void setCallStatus(CallState value) {
        this.callStatus = value;
    }

    /**
     * Gets the value of the callerAddressOfRecord property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCallerAddressOfRecord() {
        return callerAddressOfRecord;
    }

    /**
     * Sets the value of the callerAddressOfRecord property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCallerAddressOfRecord(String value) {
        this.callerAddressOfRecord = value;
    }

    /**
     * Gets the value of the calleeAddressOfRecord property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCalleeAddressOfRecord() {
        return calleeAddressOfRecord;
    }

    /**
     * Sets the value of the calleeAddressOfRecord property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCalleeAddressOfRecord(String value) {
        this.calleeAddressOfRecord = value;
    }

    /**
     * Gets the value of the callId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCallId() {
        return callId;
    }

    /**
     * Sets the value of the callId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCallId(String value) {
        this.callId = value;
    }

    /**
     * Gets the value of the callFailureReason property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCallFailureReason() {
        return callFailureReason;
    }

    /**
     * Sets the value of the callFailureReason property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCallFailureReason(String value) {
        this.callFailureReason = value;
    }

}
