// COPYRIGHT LICENSE: This information contains sample code provided in
// source code form. You may copy, modify, and distribute these sample
// programs in any form without payment to IBM for the purposes of
// developing, using, marketing or distributing application programs
// conforming to the application programming interface for the operating
// platform for which the sample code is written. Notwithstanding anything
// to the contrary, IBM PROVIDES THE SAMPLE SOURCE CODE ON AN "AS IS" BASIS
// AND IBM DISCLAIMS ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING, BUT NOT
// LIMITED TO, ANY IMPLIED WARRANTIES OR CONDITIONS OF MERCHANTABILITY,
// SATISFACTORY QUALITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, AND ANY
// WARRANTY OR CONDITION OF NON-INFRINGEMENT. IBM SHALL NOT BE LIABLE FOR ANY
// DIRECT, INDIRECT, INCIDENTAL, SPECIAL OR CONSEQUENTIAL DAMAGES ARISING OUT
// OF THE USE OR OPERATION OF THE SAMPLE SOURCE CODE. IBM HAS NO OBLIGATION
// TO PROVIDE MAINTENANCE, SUPPORT, UPDATES, ENHANCEMENTS OR MODIFICATIONS TO
// THE SAMPLE SOURCE CODE.
//
// (C) Copyright IBM Corp. 2008, 2011.
// All Rights Reserved. Licensed Materials - Property of IBM.
//
// Generated By:JAX-WS RI IBM 2.1.1 in JDK 6 (JAXB RI IBM JAXB 2.1.3 in JDK 1.6)
//


package com.ibm.ws.commsvc.webservice.impl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

@WebServiceClient(name = "ControllerService", targetNamespace = "http://impl.webservice.commsvc.ws.ibm.com/", wsdlLocation = "WEB-INF/wsdl/ControllerService.wsdl")
public class ControllerService
    extends Service
{

    private final static URL CONTROLLERSERVICE_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("file:./WEB-INF/wsdl/ControllerService.wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        CONTROLLERSERVICE_WSDL_LOCATION = url;
    }

    public ControllerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ControllerService() {
        super(CONTROLLERSERVICE_WSDL_LOCATION, new QName("http://impl.webservice.commsvc.ws.ibm.com/", "ControllerService"));
    }

    /**
     * 
     * @return
     *     returns Controller
     */
    @WebEndpoint(name = "ControllerPort")
    public Controller getControllerPort() {
        return (Controller)super.getPort(new QName("http://impl.webservice.commsvc.ws.ibm.com/", "ControllerPort"), Controller.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Controller
     */
    @WebEndpoint(name = "ControllerPort")
    public Controller getControllerPort(WebServiceFeature... features) {
        return (Controller)super.getPort(new QName("http://impl.webservice.commsvc.ws.ibm.com/", "ControllerPort"), Controller.class, features);
    }

}
