// COPYRIGHT LICENSE: This information contains sample code provided in
// source code form. You may copy, modify, and distribute these sample
// programs in any form without payment to IBM for the purposes of
// developing, using, marketing or distributing application programs
// conforming to the application programming interface for the operating
// platform for which the sample code is written. Notwithstanding anything
// to the contrary, IBM PROVIDES THE SAMPLE SOURCE CODE ON AN "AS IS" BASIS
// AND IBM DISCLAIMS ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING, BUT NOT
// LIMITED TO, ANY IMPLIED WARRANTIES OR CONDITIONS OF MERCHANTABILITY,
// SATISFACTORY QUALITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, AND ANY
// WARRANTY OR CONDITION OF NON-INFRINGEMENT. IBM SHALL NOT BE LIABLE FOR ANY
// DIRECT, INDIRECT, INCIDENTAL, SPECIAL OR CONSEQUENTIAL DAMAGES ARISING OUT
// OF THE USE OR OPERATION OF THE SAMPLE SOURCE CODE. IBM HAS NO OBLIGATION
// TO PROVIDE MAINTENANCE, SUPPORT, UPDATES, ENHANCEMENTS OR MODIFICATIONS TO
// THE SAMPLE SOURCE CODE.
//
// (C) Copyright IBM Corp. 2008, 2011.
// All Rights Reserved. Licensed Materials - Property of IBM.
//
// Generated By:JAX-WS RI IBM 2.1.1 in JDK 6 (JAXB RI IBM JAXB 2.1.3 in JDK 1.6)
//


package com.ibm.ws.commsvc.webservice.impl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import javax.xml.ws.wsaddressing.W3CEndpointReference;

@WebService(name = "Controller", targetNamespace = "http://impl.webservice.commsvc.ws.ibm.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Controller {


    /**
     * 
     * @param commWsRequest
     * @return
     *     returns javax.xml.ws.wsaddressing.W3CEndpointReference
     * @throws CTIControlException_Exception
     */
    @WebMethod
    @WebResult(name = "EndpointReference", targetNamespace = "http://www.w3.org/2005/08/addressing")
    @RequestWrapper(localName = "openSession", targetNamespace = "http://impl.webservice.commsvc.ws.ibm.com/", className = "com.ibm.ws.commsvc.webservice.impl.OpenSession")
    @ResponseWrapper(localName = "openSessionResponse", targetNamespace = "http://impl.webservice.commsvc.ws.ibm.com/", className = "com.ibm.ws.commsvc.webservice.impl.OpenSessionResponse")
    public W3CEndpointReference openSession(
        @WebParam(name = "CommWsRequest", targetNamespace = "http://impl.webservice.commsvc.ws.ibm.com/")
        CommWsRequest commWsRequest)
        throws CTIControlException_Exception
    ;

    /**
     * 
     * @param commWsRequest
     * @throws CTIControlException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "makeCall", targetNamespace = "http://impl.webservice.commsvc.ws.ibm.com/", className = "com.ibm.ws.commsvc.webservice.impl.MakeCall")
    @ResponseWrapper(localName = "makeCallResponse", targetNamespace = "http://impl.webservice.commsvc.ws.ibm.com/", className = "com.ibm.ws.commsvc.webservice.impl.MakeCallResponse")
    public void makeCall(
        @WebParam(name = "CommWsRequest", targetNamespace = "http://impl.webservice.commsvc.ws.ibm.com/")
        CommWsRequest commWsRequest)
        throws CTIControlException_Exception
    ;

    /**
     * 
     * @throws CTIControlException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "endCall", targetNamespace = "http://impl.webservice.commsvc.ws.ibm.com/", className = "com.ibm.ws.commsvc.webservice.impl.EndCall")
    @ResponseWrapper(localName = "endCallResponse", targetNamespace = "http://impl.webservice.commsvc.ws.ibm.com/", className = "com.ibm.ws.commsvc.webservice.impl.EndCallResponse")
    public void endCall()
        throws CTIControlException_Exception
    ;

    /**
     * 
     * @throws CTIControlException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "closeSession", targetNamespace = "http://impl.webservice.commsvc.ws.ibm.com/", className = "com.ibm.ws.commsvc.webservice.impl.CloseSession")
    @ResponseWrapper(localName = "closeSessionResponse", targetNamespace = "http://impl.webservice.commsvc.ws.ibm.com/", className = "com.ibm.ws.commsvc.webservice.impl.CloseSessionResponse")
    public void closeSession()
        throws CTIControlException_Exception
    ;

}
