// COPYRIGHT LICENSE: This information contains sample code provided in
// source code form. You may copy, modify, and distribute these sample
// programs in any form without payment to IBM for the purposes of
// developing, using, marketing or distributing application programs
// conforming to the application programming interface for the operating
// platform for which the sample code is written. Notwithstanding anything
// to the contrary, IBM PROVIDES THE SAMPLE SOURCE CODE ON AN "AS IS" BASIS
// AND IBM DISCLAIMS ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING, BUT NOT
// LIMITED TO, ANY IMPLIED WARRANTIES OR CONDITIONS OF MERCHANTABILITY,
// SATISFACTORY QUALITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, AND ANY
// WARRANTY OR CONDITION OF NON-INFRINGEMENT. IBM SHALL NOT BE LIABLE FOR ANY
// DIRECT, INDIRECT, INCIDENTAL, SPECIAL OR CONSEQUENTIAL DAMAGES ARISING OUT
// OF THE USE OR OPERATION OF THE SAMPLE SOURCE CODE. IBM HAS NO OBLIGATION
// TO PROVIDE MAINTENANCE, SUPPORT, UPDATES, ENHANCEMENTS OR MODIFICATIONS TO
// THE SAMPLE SOURCE CODE.
//
// (C) Copyright IBM Corp. 2008, 2011.
// All Rights Reserved. Licensed Materials - Property of IBM.
//
// Generated By:JAX-WS RI IBM 2.1.1 in JDK 6 (JAXB RI IBM JAXB 2.1.3 in JDK 1.6)
//


package com.ibm.ws.commsvc.webservice.impl;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.ibm.ws.commsvc.webservice.impl package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _CloseSessionResponse_QNAME = new QName("http://impl.webservice.commsvc.ws.ibm.com/", "closeSessionResponse");
    private final static QName _CloseSession_QNAME = new QName("http://impl.webservice.commsvc.ws.ibm.com/", "closeSession");
    private final static QName _MakeCallResponse_QNAME = new QName("http://impl.webservice.commsvc.ws.ibm.com/", "makeCallResponse");
    private final static QName _OpenSessionResponse_QNAME = new QName("http://impl.webservice.commsvc.ws.ibm.com/", "openSessionResponse");
    private final static QName _MakeCall_QNAME = new QName("http://impl.webservice.commsvc.ws.ibm.com/", "makeCall");
    private final static QName _OpenSession_QNAME = new QName("http://impl.webservice.commsvc.ws.ibm.com/", "openSession");
    private final static QName _EndCallResponse_QNAME = new QName("http://impl.webservice.commsvc.ws.ibm.com/", "endCallResponse");
    private final static QName _EndCall_QNAME = new QName("http://impl.webservice.commsvc.ws.ibm.com/", "endCall");
    private final static QName _CTIControl_QNAME = new QName("http://impl.webservice.commsvc.ws.ibm.com/", "CTIControl");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.ibm.ws.commsvc.webservice.impl
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link MakeCallResponse }
     * 
     */
    public MakeCallResponse createMakeCallResponse() {
        return new MakeCallResponse();
    }

    /**
     * Create an instance of {@link OpenSession }
     * 
     */
    public OpenSession createOpenSession() {
        return new OpenSession();
    }

    /**
     * Create an instance of {@link EndCall }
     * 
     */
    public EndCall createEndCall() {
        return new EndCall();
    }

    /**
     * Create an instance of {@link MakeCall }
     * 
     */
    public MakeCall createMakeCall() {
        return new MakeCall();
    }

    /**
     * Create an instance of {@link CTIControlException }
     * 
     */
    public CTIControlException createCTIControlException() {
        return new CTIControlException();
    }

    /**
     * Create an instance of {@link CloseSession }
     * 
     */
    public CloseSession createCloseSession() {
        return new CloseSession();
    }

    /**
     * Create an instance of {@link OpenSessionResponse }
     * 
     */
    public OpenSessionResponse createOpenSessionResponse() {
        return new OpenSessionResponse();
    }

    /**
     * Create an instance of {@link CommWsRequest }
     * 
     */
    public CommWsRequest createCommWsRequest() {
        return new CommWsRequest();
    }

    /**
     * Create an instance of {@link CallStatus }
     * 
     */
    public CallStatus createCallStatus() {
        return new CallStatus();
    }

    /**
     * Create an instance of {@link CloseSessionResponse }
     * 
     */
    public CloseSessionResponse createCloseSessionResponse() {
        return new CloseSessionResponse();
    }

    /**
     * Create an instance of {@link EndCallResponse }
     * 
     */
    public EndCallResponse createEndCallResponse() {
        return new EndCallResponse();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CloseSessionResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://impl.webservice.commsvc.ws.ibm.com/", name = "closeSessionResponse")
    public JAXBElement<CloseSessionResponse> createCloseSessionResponse(CloseSessionResponse value) {
        return new JAXBElement<CloseSessionResponse>(_CloseSessionResponse_QNAME, CloseSessionResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CloseSession }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://impl.webservice.commsvc.ws.ibm.com/", name = "closeSession")
    public JAXBElement<CloseSession> createCloseSession(CloseSession value) {
        return new JAXBElement<CloseSession>(_CloseSession_QNAME, CloseSession.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MakeCallResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://impl.webservice.commsvc.ws.ibm.com/", name = "makeCallResponse")
    public JAXBElement<MakeCallResponse> createMakeCallResponse(MakeCallResponse value) {
        return new JAXBElement<MakeCallResponse>(_MakeCallResponse_QNAME, MakeCallResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OpenSessionResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://impl.webservice.commsvc.ws.ibm.com/", name = "openSessionResponse")
    public JAXBElement<OpenSessionResponse> createOpenSessionResponse(OpenSessionResponse value) {
        return new JAXBElement<OpenSessionResponse>(_OpenSessionResponse_QNAME, OpenSessionResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MakeCall }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://impl.webservice.commsvc.ws.ibm.com/", name = "makeCall")
    public JAXBElement<MakeCall> createMakeCall(MakeCall value) {
        return new JAXBElement<MakeCall>(_MakeCall_QNAME, MakeCall.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OpenSession }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://impl.webservice.commsvc.ws.ibm.com/", name = "openSession")
    public JAXBElement<OpenSession> createOpenSession(OpenSession value) {
        return new JAXBElement<OpenSession>(_OpenSession_QNAME, OpenSession.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EndCallResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://impl.webservice.commsvc.ws.ibm.com/", name = "endCallResponse")
    public JAXBElement<EndCallResponse> createEndCallResponse(EndCallResponse value) {
        return new JAXBElement<EndCallResponse>(_EndCallResponse_QNAME, EndCallResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EndCall }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://impl.webservice.commsvc.ws.ibm.com/", name = "endCall")
    public JAXBElement<EndCall> createEndCall(EndCall value) {
        return new JAXBElement<EndCall>(_EndCall_QNAME, EndCall.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CTIControlException }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://impl.webservice.commsvc.ws.ibm.com/", name = "CTIControl")
    public JAXBElement<CTIControlException> createCTIControl(CTIControlException value) {
        return new JAXBElement<CTIControlException>(_CTIControl_QNAME, CTIControlException.class, null, value);
    }

}
