apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: acmeair-nodejs
  name: acmeair-nodejs
spec:
  type: NodePort
  ports:
  - port: 9080
    targetPort: 9080
    protocol: TCP
  selector:
    name: acmeair-nodejs