apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: acmeair-nodejs-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        name: acmeair-nodejs
    spec:
      containers:
      - image: yanglei99/acmeair-nodejs
        name: acmeair-nodejs
        ports:
        - name: http
          containerPort: 9080
        env:
        - name: MONGO_URL
          value: "mongodb://acmeair-mongo:27017/acmeair"