apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    k8s-app: acmeair-mongo
  name: acmeair-mongo-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: acmeair-mongo
    spec:
      containers:
      - image: mongo
        name: acmeair-mongo
        ports:
        - containerPort: 27017
        volumeMounts:
          - name: mongo-persistent-storage
            mountPath: /data/db
      volumes:
        - name: mongo-persistent-storage
          hostPath:
            path: /var/acmeair/db