apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: elk-sts
  labels:
    app: elk
spec:
  serviceName: elk
  replicas: 1
  template:
    metadata:
      labels:
        app: elk
    spec:
      containers:
      - image: sebp/elk
        name: elk
        ports:
        - containerPort: 5601
        - containerPort: 9200
        - containerPort: 5044
        volumeMounts:
          - name: elk-data
            mountPath: /var/lib/elasticsearch
  volumeClaimTemplates:
  - metadata:
      name: elk-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: elk
  labels:
    app: elk
spec:
  ports:
    - name: kibana
      port: 5601
      targetPort: 5601
    - name: elasticsearch
      port: 9200
      targetPort: 9200
    - name: beats
      port: 5044
      targetPort: 5044
  selector:
    app: elk
